get rid of setuid code in manage.py, set user with systemd instead
That's _really_ ugly to change permissions within manage.py script.
Especially when you should do it using system and with some handcrafted
code.

The main reason why I'm changing this is that worker can't connect to
docker unix socket using the hacky manage.py code:

ConnectionError: None: Max retries exceeded with url:
/run/docker.sock/v1.12/images/buildroot-fedora/json (Caused by redirect)

I'm not sure what's really going on, but setting user via systemd works.